name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: |
        sudo apt-get install -y libgtest-dev
        pushd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
        popd
        mkdir build
        cd build
        cmake .. -Dtest=on
        make test
